package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.Deportista;
import dao.DeportistaDao;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class AñadirDeportistaController {
	@FXML
	private Label lblNumero1;
	@FXML
	private Label lblNumero2;
	@FXML
	private Label lblNumero6;
	@FXML
	private Label lblTitulo;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtSexo;
	@FXML
	private TextField txtPeso;
	@FXML
	private TextField txtAltura;
	
	DeportistaDao dd;
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
		dd=new DeportistaDao();
		String nombre=txtNombre.getText();
		String sexo=txtSexo.getText();
		int peso=Integer.parseInt(txtPeso.getText());
		int altu=Integer.parseInt(txtAltura.getText());
		
		Deportista dep=new Deportista(nombre, sexo, peso, altu);
		dd.anadirDeporte(dep);
		
		
		Stage stage = (Stage) btnAceptar.getScene().getWindow();
		stage.close();
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cerrar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnCancelar.getScene().getWindow();
		stage.close();
	}
}
