package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.Olimpiada;
import dao.OlimpiadaDao;
import javafx.event.ActionEvent;

public class AñadirOlimpiadaController {
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtAnio;
	@FXML
	private TextField txtTemporada;
	@FXML
	private TextField txtCiudad;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	
	private OlimpiadaDao od;
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
		od=new OlimpiadaDao();
		String nombre=txtNombre.getText();
		int anio=Integer.parseInt(txtAnio.getText());
		String tempo=txtTemporada.getText();
		String ciudad=txtCiudad.getText();
		Olimpiada ol=new Olimpiada(nombre, anio, tempo, ciudad);
		if(od.comprobarOlimpiada(ol)) {
			System.out.println("existe");
		}else {
			od.anadirOlimpiada(ol);
		}
		Stage stage = (Stage) btnAceptar.getScene().getWindow();
		stage.close();
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnAceptar.getScene().getWindow();
		stage.close();
	}
}
