package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.stage.Window;
import model.Deporte;
import model.Olimpiada;
import dao.OlimpiadaDao;
import javafx.event.ActionEvent;

public class AñadirOlimpiadaController {
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtAnio;
	@FXML
	private TextField txtTemporada;
	@FXML
	private TextField txtCiudad;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
    @FXML
    private Label lblTitulo;
    
	private OlimpiadaDao od;
	private String nomAnt;
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
		od=new OlimpiadaDao();
		String nombre=txtNombre.getText();
		int anio=Integer.parseInt(txtAnio.getText());
		String tempo=txtTemporada.getText();
		String ciudad=txtCiudad.getText();
		Olimpiada ol=new Olimpiada(nombre, anio, tempo, ciudad);
		
		if(lblTitulo.getText().equals("Modificar Olimpiada")) {
			if(comprobar().length()==0) {
				od.modificarOlimpiada(ol, nomAnt);
				info(btnAceptar.getScene().getWindow());
				Stage stage = (Stage) btnAceptar.getScene().getWindow();
				stage.close();
			}else {
				error(btnAceptar.getScene().getWindow());
			}
			

		}else {
			if(comprobar().length()==0) {
				od.anadirOlimpiada(ol);
				info(btnAceptar.getScene().getWindow());
				Stage stage = (Stage) btnAceptar.getScene().getWindow();
				stage.close();
			}else {
				error(btnAceptar.getScene().getWindow());
			}
				
			
		}
		
		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnAceptar.getScene().getWindow();
		stage.close();
	}
	public TextField getTxtNombre() {
		return txtNombre;
	}
	public TextField getTxtAnio() {
		return txtAnio;
	}
	public TextField getTxtTemporada() {
		return txtTemporada;
	}
	public TextField getTxtCiudad() {
		return txtCiudad;
	}
	public Label getLblTitulo() {
		return lblTitulo;
	}
	public void setNomAnt(String nomAnt) {
		this.nomAnt = nomAnt;
	}
	public String comprobar() {
		String fallo="";
		if(txtNombre.getText().length()==0) {
			fallo+="\n El campo del nombre de la Olimpiada tiene que tener contenido";
		}
		if(txtCiudad.getText().length()==0) {
			fallo+="\n El campo del Ciudad de la Olimpiada tiene que tener contenido";
		}
		if(txtAnio.getText().length()==0) {
			fallo+="\n El campo del año de la Olimpiada tiene que tener contenido";
		}
		try {
			int i=Integer.parseInt(txtAnio.getText());
		} catch (NumberFormatException e) {
			// TODO: handle exception
			fallo+="\n El campo del año de la Olimpiada tiene que ser numeros";
		}
		if(txtTemporada.getText().length()==0) {
			fallo+="\n El campo de la temporada de la Olimpiada tiene que tener contenido";
		}
		if(!txtTemporada.getText().equals("Winter") || !txtTemporada.getText().equals("Summer")) {
			fallo+="\n El campo de la temporada de la Olimpiada tiene que ser Winter o Summer";
		}
		String nombre=txtNombre.getText();
		int anio=Integer.parseInt(txtAnio.getText());
		String tempo=txtTemporada.getText();
		String ciudad=txtCiudad.getText();
		Olimpiada ol=new Olimpiada(nombre, anio, tempo, ciudad);
		if(od.sacarOlimpiada().contains(ol)) {
			fallo+="\n Esa Olimpiada ya existe";
		}
		
		
		return fallo;
	}
	public void error (Window win) {
		Alert alert;
		String texto=comprobar();
		alert = new Alert(Alert.AlertType.ERROR);
		alert.setContentText(texto);
		alert.setHeaderText(null);
		alert.initOwner(win);
		alert.setTitle("ERROR");
		alert.showAndWait();
	}
	public void info(Window win) {
		Alert alert;
		alert = new Alert(Alert.AlertType.INFORMATION);
		alert.setContentText("ACCION HECHA CORRECTAMENTE");
		alert.setHeaderText(null);
		alert.initOwner(win);
		alert.setTitle("INFO");
		alert.showAndWait();
	}
}
