package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.Deporte;
import model.Evento;
import model.Olimpiada;
import dao.DeporteDao;
import dao.EventoDao;
import dao.OlimpiadaDao;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class AñadirController {
	@FXML
	private Label lblNumero1;
	@FXML
	private Label lblNumero2;
	@FXML
	private Label lblNumero3;
	@FXML
	private Label lblNumero4;
	@FXML
	private Label lblNumero5;
	@FXML
	private Label lblNumero6;
	@FXML
	private TextField txtNumero1;	//Nombre del Evento
	@FXML
	private TextField txtNumero2;	//Nombre del Olimpiada de Evento
	@FXML
	private TextField txtNumero3;	//Año de la Olimpiada de Evento
	@FXML
	private TextField txtNumero4;	//Temporada de la Olimpiada de Evento
	@FXML
	private TextField txtNumero5;	//Ciudad de la Olimpiada de Evento
	@FXML	
	private TextField txtNumero6;   //Nombre del Deporte
	@FXML
	private Label lblTitulo;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	
	private DeporteDao dp;
	private EventoDao ed;
	private OlimpiadaDao od;
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated.
		//DECLARAR LOS DAO
		dp=new DeporteDao();
		ed=new EventoDao();
		od=new OlimpiadaDao();
		//CREAR LOS ELEMENTOS
		Evento ev=new Evento(txtNumero1.getText(), txtNumero2.getText(), Integer.parseInt(txtNumero3.getText()), txtNumero4.getText(), txtNumero5.getText(), txtNumero5.getText());
		Deporte dep=new Deporte(txtNumero6.getText());
		Olimpiada ol=new Olimpiada(txtNumero2.getText(), Integer.parseInt(txtNumero3.getText()), txtNumero4.getText(), txtNumero5.getText());
		//COMPROBAR SI EXISTE DEPORTE Y SACAR EL ID 
		if(dp.comprobarDeporte(dep)==false) {
			dp.anadirDeporte(dep);
		}
		int id_Deporte=dp.sacarId(dep);
		//COMPROBAR SI EXISTE OLIMPIADA Y SACAR EL ID 
		if(od.comprobarOlimpiada(ol)==false) {
			od.anadirOlimpiada(ol);
		}
		int id_Olimpiada=od.sacarId(ol);
		//AÑADIR EVENTO
		ed.anadirEvento(ev, id_Olimpiada, id_Deporte);
		//PARA QUE SE CIERRE AL DARLE ACEPTAR
		Stage stage = (Stage) btnAceptar.getScene().getWindow();
		stage.close();
		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cerrar(ActionEvent event) {
		// TODO Autogenerated
		//PARA QUE SE CIERRE AL DARLE CANCELAR
		Stage stage = (Stage) btnCancelar.getScene().getWindow();
		stage.close();
	}
}
