package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;
import model.Deportista;
import model.Equipos;
import model.Evento;
import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import dao.DeportistaDao;
import dao.EquipoDao;
import dao.EventoDao;
import dao.ParticipacionDao;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.RadioButton;

public class AñadirParticipacionController implements Initializable{
	@FXML
	private Label lblNumero2;
	@FXML
	private Label lblNumero6;
	@FXML
	private Label lblTitulo;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	@FXML
	private ComboBox comboDeportista;
	@FXML
	private ComboBox comboEvento;
	@FXML
	private RadioButton rbOro;
	@FXML
	private ToggleGroup medalla;
	@FXML
	private RadioButton rbPlata;
	@FXML
	private RadioButton rbBronze;
	@FXML
	private RadioButton rbNada;
	@FXML
	private ComboBox comboEquipo;
	@FXML
	private TextField txtEdad;
	ParticipacionDao pd;
	EventoDao evd;
	EquipoDao eqd;
	DeportistaDao dd;
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		String med;
		//Saber que medalla a conseguido
		if(rbOro.isSelected()) {
			med=rbOro.getText();
		}else {
			if(rbPlata.isSelected()) {
				med=rbPlata.getText();
			}else {
				if(rbBronze.isSelected()) {
					med=rbBronze.getText();
				}else {
					med="";
				}
			}
		}
		//Buscar el id deportista
		Deportista dep=(Deportista) comboDeportista.getSelectionModel().getSelectedItem();
		int id_deportista=dd.bucarId(dep);
		System.out.println(id_deportista);
		//Buscar el id Equipo
		Equipos equip=(Equipos) comboEquipo.getSelectionModel().getSelectedItem();
		int id_equipo=eqd.bucarId(equip);
		System.out.println("bbbbbbbbbbb");
		//Buscar el id Evento
		Evento ev=(Evento) comboEvento.getSelectionModel().getSelectedItem();
		int id_evento=evd.sacarId(ev);
		System.out.println("cccccccccccc");
		//sacar los otros datos
		int edad=Integer.parseInt(txtEdad.getText());
		
		pd.anadirParticipacion(edad, med, id_deportista, id_evento, id_equipo);
		
		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cerrar(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		pd=new ParticipacionDao();
		evd=new EventoDao();
		eqd=new EquipoDao();
		dd=new DeportistaDao();
		comboDeportista.setItems(dd.sacarDeportistas());
		comboEvento.setItems(evd.cargarEvento());
		comboEquipo.setItems(eqd.sacarEquipos());
	}
}
