package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.stage.Window;
import model.Deporte;
import model.Equipos;

import java.net.URL;
import java.util.ResourceBundle;

import dao.EquipoDao;
import javafx.event.ActionEvent;

public class AñadirEquipoController implements Initializable{
	@FXML
	private Button btnAnadir;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtDeporte;
	@FXML
	private TextField txtIniciales;

	@FXML
    private Label lblTitulo;
	private EquipoDao eqD;
	private String nomAnt;
	// Event Listener on Button[#btnAnadir].onAction

	@FXML
	public void aceptar(ActionEvent event)  {
		// TODO Autogenerated
		eqD=new EquipoDao();
		
		if(lblTitulo.getText().equals("Modificar Equipo")) {
			Equipos eq=new Equipos(txtDeporte.getText(), txtIniciales.getText());
			if(comprobar().length()==0) {
				
				eqD.modificarEquipo(eq, nomAnt);
				info(btnAnadir.getScene().getWindow());
				Stage stage = (Stage) btnAnadir.getScene().getWindow();
				stage.close();
			}else {
				error(btnAnadir.getScene().getWindow());
			}
		}else {
			if(comprobar().length()==0) {
				Equipos eq=new Equipos(txtDeporte.getText(), txtIniciales.getText());
				eqD.anadirEquipo(eq);
				info(btnAnadir.getScene().getWindow());
				Stage stage = (Stage) btnAnadir.getScene().getWindow();
				stage.close();
			}else {
				error(btnAnadir.getScene().getWindow());
			}
		}
		
		

		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnAnadir.getScene().getWindow();
		stage.close();
	}
    public TextField getTxtDeporte() {
		return txtDeporte;
	}
	public TextField getTxtIniciales() {
		return txtIniciales;
	}
	public Label getLblTitulo() {
		return lblTitulo;
	}
	public void setNomAnt(String nomAnt) {
		this.nomAnt = nomAnt;
	}
	public String comprobar() {
		String fallo="";
		if(txtDeporte.getText().length()==0) {
			fallo+="\n El campo del nombre del Equipo tiene que tener contenido";
		}
		
		Equipos equi=new Equipos(txtDeporte.getText(),txtIniciales.getText());
		if(eqD.sacarEquipos().contains(equi)) {
			fallo+="\n Ese Equipo ya existe";
		}
		
		
		return fallo;
	}
	public void error () {
		Alert alert;
		String texto=comprobar();
		alert = new Alert(Alert.AlertType.ERROR);
		alert.setContentText(texto);
		alert.setHeaderText(null);
		alert.setTitle("ERROR");
		alert.showAndWait();
	}
	public void info() {
		Alert alert;
		alert = new Alert(Alert.AlertType.INFORMATION);
		alert.setContentText("ACCION HECHA CORRECTAMENTE");
		alert.setHeaderText(null);
		alert.setTitle("INFO");
		alert.showAndWait();
	}
	public void rellenar(String titulo) {
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		eqD=new EquipoDao();
	}
}
