package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.stage.Window;
import model.Deportista;
import model.Olimpiada;
import dao.DeportistaDao;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class AñadirDeportistaController {
	@FXML
	private Label lblNumero1;
	@FXML
	private Label lblNumero2;
	@FXML
	private Label lblNumero6;
	@FXML
	private Label lblTitulo;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtSexo;
	@FXML
	private TextField txtPeso;
	@FXML
	private TextField txtAltura;
	
	private String nomAnt;
	private DeportistaDao dd;
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
		dd=new DeportistaDao();
		String nombre=txtNombre.getText();
		String sexo=txtSexo.getText();
		int peso=Integer.parseInt(txtPeso.getText());
		int altu=Integer.parseInt(txtAltura.getText());
		Deportista dep=new Deportista(nombre, sexo, peso, altu);
		if(lblTitulo.getText().equals("Modificar Deportista")) {
			if(comprobar().length()==0) {
				
				dd.modificarDeportista(dep, nomAnt);
				info(btnAceptar.getScene().getWindow());
				Stage stage = (Stage) btnAceptar.getScene().getWindow();
				stage.close();
			}else {
				error(btnAceptar.getScene().getWindow());
			}
			
		}else {
			if(comprobar().length()==0) {
				dd.anadirDeporte(dep);
				info(btnAceptar.getScene().getWindow());
				Stage stage = (Stage) btnAceptar.getScene().getWindow();
				stage.close();
			}else {
				error(btnAceptar.getScene().getWindow());
			}

		}
		
		
		
		
		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cerrar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnCancelar.getScene().getWindow();
		stage.close();
	}
	public Label getLblTitulo() {
		return lblTitulo;
	}
	public TextField getTxtNombre() {
		return txtNombre;
	}
	public TextField getTxtSexo() {
		return txtSexo;
	}
	public TextField getTxtPeso() {
		return txtPeso;
	}
	public TextField getTxtAltura() {
		return txtAltura;
	}
	public void setNomAnt(String nomAnt) {
		this.nomAnt = nomAnt;
	}
	public String comprobar() {
		String fallo="";
		if(txtNombre.getText().length()==0) {
			fallo+="\n El campo del nombre  tiene que tener contenido";
		}
		if(txtAltura.getText().length()==0) {
			fallo+="\n El campo altura tiene que tener contenido";
		}
		if(txtPeso.getText().length()==0) {
			fallo+="\n El campo peso tiene que tener contenido";
		}
		try {
			int i=Integer.parseInt(txtPeso.getText());
		} catch (NumberFormatException e) {
			// TODO: handle exception
			fallo+="\n El campo peso tiene que ser numeros";
		}
		if(txtSexo.getText().length()==0) {
			fallo+="\n El campo sexo tiene que tener contenido";
		}
		if(!txtSexo.getText().equals("M") || !txtSexo.getText().equals("F")) {
			fallo+="\n El campo sexo tiene que ser M o F";
		}
		String nombre=txtNombre.getText();
		String sexo=txtSexo.getText();
		int peso=Integer.parseInt(txtPeso.getText());
		int altu=Integer.parseInt(txtAltura.getText());
		Deportista dep=new Deportista(nombre, sexo, peso, altu);
		if(dd.sacarDeportistas().contains(dep)) {
			fallo+="\n Esa Olimpiada ya existe";
		}
		
		
		return fallo;
	}
	public void error (Window win) {
		Alert alert;
		String texto=comprobar();
		alert = new Alert(Alert.AlertType.ERROR);
		alert.setContentText(texto);
		alert.setHeaderText(null);
		alert.initOwner(win);
		alert.setTitle("ERROR");
		alert.showAndWait();
	}
	public void info(Window win) {
		Alert alert;
		alert = new Alert(Alert.AlertType.INFORMATION);
		alert.setContentText("ACCION HECHA CORRECTAMENTE");
		alert.setHeaderText(null);
		alert.initOwner(win);
		alert.setTitle("INFO");
		alert.showAndWait();
	}
}
