package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.Deporte;
import dao.DeporteDao;
import javafx.event.ActionEvent;

public class AñadirDeporteController {
	@FXML
	private Button btnAnadir;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtDeporte;
	DeporteDao dd;
	// Event Listener on Button[#btnAnadir].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		dd=new DeporteDao();
		Deporte dep=new Deporte(txtDeporte.getText());
		dd.anadirDeporte(dep);
		Stage stage = (Stage) btnAnadir.getScene().getWindow();
		stage.close();
	
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnCancelar.getScene().getWindow();
		stage.close();
	}
}
