package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.stage.Window;
import model.Deporte;
import model.Evento;
import dao.DeporteDao;
import javafx.event.ActionEvent;

public class AñadirDeporteController {
	@FXML
	private Button btnAnadir;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtDeporte;

    @FXML
    private Label lblTitulo;
    
    private String nomAnt;

	private DeporteDao dd;
	// Event Listener on Button[#btnAnadir].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		dd=new DeporteDao();
		Deporte dep=new Deporte(txtDeporte.getText());
		System.out.println(lblTitulo.getText());
		if(lblTitulo.getText().equals("AÑADIR DEPORTE")) {
			if(comprobar().length()==0) {
				
				dd.anadirDeporte(dep);
				System.out.println("aaaaaaaaaa");
				info(btnAnadir.getScene().getWindow());
				Stage stage = (Stage) btnAnadir.getScene().getWindow();
				stage.close();
			}else {
				error(btnAnadir.getScene().getWindow());
			}
			
			
		}else {
			if(comprobar().length()==0) {
				dd.modificarDeporte(dep, nomAnt);
				info(btnAnadir.getScene().getWindow());
				Stage stage = (Stage) btnAnadir.getScene().getWindow();
				stage.close();
			}else {
				error(btnAnadir.getScene().getWindow());
			}
			
		}
	
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnCancelar.getScene().getWindow();
		stage.close();
	}
	public TextField getTxtDeporte() {
		return txtDeporte;
	}
	public Label getLblTitulo() {
		return lblTitulo;
	}
	public void setNomAnt(String nomAnt) {
		this.nomAnt = nomAnt;
	}
	public String comprobar() {
		String fallo="";
		if(txtDeporte.getText().length()==0) {
			fallo+="\n El campo del nombre Deporte tiene que tener contenido";
		}
		Deporte dep=new Deporte(txtDeporte.getText());
		if(dd.sacarDeportes().contains(dep)) {
			fallo+="\n Ese deporte ya existe";
		}
		
		
		return fallo;
	}
	public void error (Window win) {
		Alert alert;
		String texto=comprobar();
		alert = new Alert(Alert.AlertType.ERROR);
		alert.setContentText(texto);
		alert.setHeaderText(null);
		alert.initOwner(win);
		alert.setTitle("ERROR");
		alert.showAndWait();
	}
	public void info(Window win) {
		Alert alert;
		alert = new Alert(Alert.AlertType.INFORMATION);
		alert.setContentText("ACCION HECHA CORRECTAMENTE");
		alert.setHeaderText(null);
		alert.initOwner(win);
		alert.setTitle("INFO");
		alert.showAndWait();
	}
}
