package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.Deporte;
import model.Evento;
import model.Olimpiada;

import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ResourceBundle;

import conexionBD.ConexionDB;
import dao.DeporteDao;
import dao.EventoDao;
import dao.OlimpiadaDao;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class AñadirController implements Initializable{

	   @FXML
	    private Button btnAceptar;

	    @FXML
	    private Button btnCancelar;

	    @FXML
	    private ComboBox<Deporte> comboDeporte;

	    @FXML
	    private ComboBox<Olimpiada> comboOlimpiada;

	    @FXML
	    private Label lblNumero1;

	    @FXML
	    private Label lblNumero2;

	    @FXML
	    private Label lblNumero6;

	    @FXML
	    private Label lblTitulo;

	    @FXML
	    private TextField txtNumero1;
	
	private DeporteDao dp;
	private EventoDao ed;
	private OlimpiadaDao od;
	// Event Listener on Button[#btnAceptar].onAction
	
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated.
		
		//CREAR LOS ELEMENTOS
		Evento ev=new Evento(txtNumero1.getText());
		Deporte dep=comboDeporte.getSelectionModel().getSelectedItem();
		Olimpiada ol=comboOlimpiada.getSelectionModel().getSelectedItem();
		//SACAR IDs
		int id_Deporte=dp.sacarId(dep);
		
		int id_Olimpiada=od.sacarId(ol);
		//AÑADIR EVENTO
		ed.anadirEvento(ev, id_Olimpiada, id_Deporte);
		//PARA QUE SE CIERRE AL DARLE ACEPTAR
		Stage stage = (Stage) btnAceptar.getScene().getWindow();
		stage.close();
		
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cerrar(ActionEvent event) {
		// TODO Autogenerated
		//PARA QUE SE CIERRE AL DARLE CANCELAR
		Stage stage = (Stage) btnCancelar.getScene().getWindow();
		stage.close();
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		//DECLARAR LOS DAO
		dp=new DeporteDao();
		ed=new EventoDao();
		od=new OlimpiadaDao();
		this.comboDeporte.setItems(dp.sacarDeportes());
		comboDeporte.getSelectionModel().select(0);
		this.comboOlimpiada.setItems(od.sacarOlimpiada());
		comboOlimpiada.getSelectionModel().select(0);
	}




}
