package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import dao.DeporteDao;
import dao.DeportistaDao;
import dao.EquipoDao;
import dao.OlimpiadaDao;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.stage.Window;
import model.Deporte;
import model.Deportista;
import model.Equipos;
import model.Olimpiada;

public class listaController implements Initializable{
	@FXML
	private Label lblTitulo;
	@FXML
	private ListView listObjetos;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	private DeporteDao dd;

	private int tipo;//1=modificar 2=eliminar
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void Aceptar(ActionEvent event) {
		// TODO Autogenerated
		if(listObjetos.getSelectionModel().getSelectedItem()!=null) {
			if(tipo==1) {
				//System.out.println(lblTitulo.getText());
				if(lblTitulo.getText().equals("Deportes")) {
					FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/AñadirDeporte.fxml"));
					Parent root;
					
					try {
						root = loader.load();
						Scene newScene = new Scene(root);
						Stage newStage = new Stage();
						AñadirDeporteController control = loader.getController();
						control.getLblTitulo().setText("Modificar Deporte");
						Deporte dep=(Deporte) listObjetos.getSelectionModel().getSelectedItem();
						control.getTxtDeporte().setText(dep.getDeporte());
						control.setNomAnt(dep.getDeporte());
						newStage.initModality(Modality.APPLICATION_MODAL);
						newStage.setScene(newScene);
						newStage.setTitle("Deportes");
						newStage.showAndWait();
						
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					listObjetos.setItems(dd.sacarDeportes());
				}
				if(lblTitulo.getText().equals("Deportistas")) {
					FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/AñadirDeportista.fxml"));
					Parent root;
					DeportistaDao ded=new DeportistaDao();
					try {
						root = loader.load();
						Scene newScene = new Scene(root);
						Stage newStage = new Stage();
						AñadirDeportistaController control = loader.getController();
						control.getLblTitulo().setText("Modificar Deportista");
						Deportista depo=(Deportista) listObjetos.getSelectionModel().getSelectedItem();
						control.getTxtNombre().setText(depo.getNombre());
						control.getTxtAltura().setText(String.valueOf(depo.getAltura()));
						control.getTxtPeso().setText(String.valueOf(depo.getPeso()));
						control.getTxtSexo().setText(depo.getSexo());
						control.setNomAnt(depo.getNombre());
						
						newStage.initModality(Modality.APPLICATION_MODAL);
						newStage.setScene(newScene);
						newStage.setTitle("Deportes");
						newStage.showAndWait();
						listObjetos.setItems(ded.sacarDeportistas());
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
				if(lblTitulo.getText().equals("Equipos")) {
					FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/AñadirEquipo.fxml"));
					Parent root;
					EquipoDao eqd=new EquipoDao();
					try {
						root = loader.load();
						Scene newScene = new Scene(root);
						Stage newStage = new Stage();
						AñadirEquipoController control = loader.getController();
						control.getLblTitulo().setText("Modificar Equipo");
						Equipos eq=(Equipos) listObjetos.getSelectionModel().getSelectedItem();
						control.getTxtDeporte().setText(eq.getNombre());
						control.getTxtIniciales().setText(eq.getIniciales());
						control.setNomAnt(eq.getNombre());
						newStage.initModality(Modality.APPLICATION_MODAL);
						newStage.setScene(newScene);
						newStage.setTitle("Equipos");
						newStage.showAndWait();
						listObjetos.setItems(eqd.sacarEquipos());
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
				if(lblTitulo.getText().equals("Olimpiadas")) {
					FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/AñadirOlimpiada.fxml"));
					Parent root;
					OlimpiadaDao od=new OlimpiadaDao();
					try {
						root = loader.load();
						Scene newScene = new Scene(root);
						Stage newStage = new Stage();
						AñadirOlimpiadaController control = loader.getController();
						control.getLblTitulo().setText("Modificar Olimpiada");
						Olimpiada ol=(Olimpiada) listObjetos.getSelectionModel().getSelectedItem();
						control.getTxtAnio().setText(String.valueOf(ol.getAnio()));
						control.getTxtCiudad().setText(ol.getCiudad());
						control.getTxtNombre().setText(ol.getNombre());
						control.getTxtTemporada().setText(ol.getTemporada());
						control.setNomAnt(ol.getNombre());
						
						newStage.initModality(Modality.APPLICATION_MODAL);
						newStage.setScene(newScene);
						newStage.setTitle("Equipos");
						newStage.showAndWait();
						listObjetos.setItems(od.sacarOlimpiada());
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
				
				

			}else {
				if(lblTitulo.getText().equals("Deportes")) {
					DeporteDao dd=new DeporteDao();
					Deporte dep=(Deporte) listObjetos.getSelectionModel().getSelectedItem();
					int idDeporte=dd.sacarId(dep);
					dd.eliminarDeporte(idDeporte);
					listObjetos.setItems(dd.sacarDeportes());				
				}
				if(lblTitulo.getText().equals("Deportistas")) {
					DeportistaDao dd=new DeportistaDao();
					Deportista dep=(Deportista) listObjetos.getSelectionModel().getSelectedItem();
					int idDeportista=dd.bucarId(dep);
					dd.eliminarDeportista(idDeportista);
					listObjetos.setItems(dd.sacarDeportistas());				
				}
				if(lblTitulo.getText().equals("Equipos")) {
					EquipoDao eqd=new EquipoDao();
					Equipos eq=(Equipos) listObjetos.getSelectionModel().getSelectedItem();
					int idEquipo=eqd.bucarId(eq);
					eqd.eliminarEquipo(idEquipo);
					listObjetos.setItems(eqd.sacarEquipos());				
				}
				if(lblTitulo.getText().equals("Olimpiadas")) {
					OlimpiadaDao olD=new OlimpiadaDao();
					Olimpiada ol= (Olimpiada) listObjetos.getSelectionModel().getSelectedItem();
					int idOlimpiada=olD.sacarId(ol);
					olD.eliminarOlimpiada(idOlimpiada);
					listObjetos.setItems(olD.sacarOlimpiada());				
				}
			}
		}

	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) btnAceptar.getScene().getWindow();
		stage.close();
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		listObjetos.getSelectionModel().select(0);
		this.dd=new DeporteDao();
	}

	public ListView getListObjetos() {
		return listObjetos;
	}
	public Label getLblTitulo() {
		return lblTitulo;
	}
	public void setTipo(int tipo) {
		this.tipo = tipo;
	}
	
}
