package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

public class listaController {
	@FXML
	private Label lblTitulo;
	@FXML
	private ListView listObjetos;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void Aceptar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
