package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.stage.Window;
import model.Persona;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class EjercicioGController implements Initializable{
	@FXML
	private TableView tablaPersona;
	@FXML
	private TableColumn colNombre1;
	@FXML
	private TableColumn colApellido1;
	@FXML
	private TableColumn colEdad1;
	@FXML
	private Button btnAñadir;
	@FXML
	private Button btnModificar;
	@FXML
	private Button btnEliminar;
	@FXML
	private TextField txtBuscar;
	@FXML
	private Button btnExportar;
	@FXML
	private Button btnImportar;
	private ObservableList<Persona> listaPersona;

	// Event Listener on Button[#btnAñadir].onAction
	@FXML
	public void anadirPersona(ActionEvent event) {
		abrirVentana(1);
		
	}
	
	@FXML
	public void modificarPersona(ActionEvent event) {
		abrirVentana(0);
		
	}
	
	public void abrirVentana(int tipo) {
		//CREAR LA VENTANA AÑADIR PERSONA
		 try{
	         FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/NuevoUsuarioFXML.fxml"));
	         Parent root = loader.load();
	         Scene newScene = new Scene(root);
	         Stage newStage = new Stage();
	         NuevoUsuarioFXMLController control= loader.getController();
	         control.cargarLista(listaPersona);
	         newStage.initModality(Modality.APPLICATION_MODAL);
	         newStage.initOwner(this.btnAñadir.getScene().getWindow());
	         newStage.setScene(newScene);
	         if(tipo==1) {
	        	 newStage.setTitle("Nueva Persona");
		         tablaPersona.refresh();
		         newStage.showAndWait ();
		         // System.out.println(control.comprobar());
		         if(control.comprobar().length()==0) {
		        	  Persona p= control.getP();
			          listaPersona.add(p);
			          tablaPersona.refresh();
			          
		         }
	         }
	         if(tipo==0) {
	        	 newStage.setTitle("Modificar Persona");
		         tablaPersona.refresh();
		         newStage.showAndWait ();
		         // System.out.println(control.comprobar());
		         if(control.comprobar().length()==0) {
		        	  Persona p =(Persona)tablaPersona.getSelectionModel().getSelectedItem();
		        	  p.setNombre(control.getTxtNombre().getText());
		        	  p.setApellido(control.getTxtApellido().getText());
		        	  p.setEdad(control.getTxtEdad().getText());
			          tablaPersona.refresh();
			          
		         }
	         }

	   } catch (IOException e) {
	       Alert alert = new Alert(Alert.AlertType.ERROR);
	       alert.setHeaderText(null);
	       alert.setTitle("Error");
	       alert.setContentText(e.getMessage());
	       alert.showAndWait();
	   }
	}
	void eliminar() {
		Persona perselect= (Persona) tablaPersona.getSelectionModel().getSelectedItem();
		listaPersona.remove(perselect);
	}
	// Event Listener on Button[#btnEliminar].onAction
	@FXML
	public void eliminarPersona(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#txtBuscar].onAction
	@FXML
	public void buscar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExportar].onAction
	@FXML
	public void Exportar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnImportar].onAction
	@FXML
	public void Importar(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		listaPersona = FXCollections.observableArrayList();
//		Persona p = new Persona("a","b","5");
//		listaPersona.add(p);
		tablaPersona.setItems(listaPersona);
		colNombre1.setCellValueFactory(new PropertyValueFactory<>("nombre"));
		colApellido1.setCellValueFactory(new PropertyValueFactory<>("apellido"));
		colEdad1.setCellValueFactory(new PropertyValueFactory<>("edad"));
		//tablaPersona.getColumns().addAll(colNombre1,colApellido1,colEdad1);
		
		
	}
	public TableView getTablaPersona() {
		return tablaPersona;
	}

	public ObservableList<Persona> getListaPersona() {
		return listaPersona;
	}

}
