package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.RadioButton;

public class EjercicioL_Anadir_AeropuertoController implements Initializable{
	@FXML
	private Label lblNTrabajadores;
	@FXML
	private RadioButton rbPublico;
	@FXML
	private RadioButton rbPrivado;
	@FXML
	private Button btnGuardar;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtPais;
	@FXML
	private TextField txtCiudad;
	@FXML
	private TextField txtCalle;
	@FXML
	private TextField txtNumero;
	@FXML
	private TextField txtInaguracion;
	@FXML
	private TextField txtCapacidad;
	@FXML
	private TextField txtFinanOsocios;
	@FXML
	private TextField txtNTrabajadores;
	@FXML
	private Label lblSocios;
    @FXML
    private Label lblFinanciacion;

	// Event Listener on Button[#btnGuardar].onAction
	@FXML
	public void aniadirAeropuerto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void salir(ActionEvent event) {
		// TODO Autogenerated
	}
	  @FXML
	void cambiar(ActionEvent event) {
		  if(rbPrivado.isSelected()) {
			  
		  }
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		rbPrivado.setSelected(true);
		lblNTrabajadores.setVisible(false);
		lblFinanciacion.setVisible(false);
		txtNTrabajadores.setVisible(false);
		
	}
}
